### ISSUE TITLE
Where is source of derive_merge crate?

### ISSUE THREAD

**Issue by kolbma** [reticenceji/merge_struct#1]
Hi Ji,
don't you have a GH repo for the dependent crate https://docs.rs/derive_merge/0.1.0/derive_merge/ ?
Thanks Markus

**Comment by reticenceji** [comment]
Yes, but I don't push it to github. Maybe you can take a look at <https://docs.rs/derive_merge/0.1.0/src/derive_merge/lib.rs.html> since it has only one file.

If you want the project I can push it to github.

**Comment by kolbma** [comment]
@reticenceji For me you don't have to do it. Just wanted to get sure that I have not missed some place to check out. ;-)

Thx
